# Generated by Django 5.2.17 on 2026-09-21 12:55

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_award'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['-is_featured', '-year', 'title']},
        ),
        migrations.AddField(
            model_name='award',
            name='certificate_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='award',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='award',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='award',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='award',
            name='level',
            field=models.CharField(choices=[('internal', 'Internal Kampus'), ('regional', 'Regional'), ('national', 'Nasional'), ('international', 'Internasional')], default='national', max_length=15),
        ),
        migrations.AddField(
            model_name='award',
            name='placement',
            field=models.CharField(choices=[('first', 'Juara 1'), ('second', 'Juara 2'), ('third', 'Juara 3'), ('finalist', 'Finalis'), ('other', 'Penghargaan Lain')], default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='award',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
